CREATE OR REPLACE TRIGGER update_amount
    AFTER DELETE OR INSERT
    ON DEPARTMENTS
    FOR EACH ROW
BEGIN
    CASE
        WHEN INSERTING
            THEN UPDATE LOCATIONS SET department_amount = DEPARTMENT_AMOUNT + 1 WHERE LOCATION_ID = :new.location_id;
        WHEN DELETING
            THEN UPDATE LOCATIONS SET DEPARTMENT_AMOUNT = DEPARTMENT_AMOUNT - 1 WHERE LOCATION_ID = :new.location_id;
        end case;
end;